### ISSUE TITLE
have you build yet cm for the smt-705?

### ISSUE THREAD

**Issue by schwabe93** [lssjbrolli/android_device_samsung_klimtlte-old#1]
Hi have you yet build a cm version for tab s lte ?

**Comment by lssjbrolli** [comment]
yes

4g, camera and mic doesn't work yet

**Comment by schwabe93** [comment]
Ok, do you need a tester for your builds?

**Comment by schwabe93** [comment]
So i have build it for my own on my vps, but i get into bootloop can you provide one of your builds

**Comment by lssjbrolli** [comment]
here you go: https://www.dropbox.com/s/hbc8tb5wjhx1c61/cm-11-20150125-UNOFFICIAL-klimtlte.zip?dl=0

feel free to test and add bug reports.

i also take patches :)

**Comment by tubalu** [comment]
thanks. it's a surprise.

**Comment by tubalu** [comment]
when I try to flash, it said "this device is klimtwifi" , mine is sm-t705

**Comment by lssjbrolli** [comment]
does your device have 4G?

**Comment by lssjbrolli** [comment]
if your device is wifi only you can use eousphoros port @ http://forum.xda-developers.com/galaxy-tab-s/orig-development/unofficial-cyanogenmod-11-android-4-4-4-t2835170

**Comment by tubalu** [comment]
I removed the first line of the update script, and flash it. I have H+
connection, and can make phone call.

**Comment by schwabe93** [comment]
doyou remove this line: assert(getprop("ro.product.device") == "klimtlte" ||
       getprop("ro.build.product") == "klimtlte" ||
       abort("This package is for device: klimtlte; this device is " + getprop("ro.product.device") + "."););

or what? i also have build cwm recovery for the Smt-705 but my Rom that i build dont boot
@lssjbrolli what vendor source do you use? the kernel source and device source i used from your github account?

**Comment by tubalu** [comment]
yes, I removed the line you mentioned. I use the twrp recovery image.

**Comment by lssjbrolli** [comment]
@schwabe93  yes the rom was built using the sources from my account, with binary blobs from T705XXU1ANF8_T705LUX1ANK1_LUX image.

**Comment by lssjbrolli** [comment]
@tubalu Can you provide a link to the recovery image you are using?
