### ISSUE TITLE
Can you provide a download link to test

### ISSUE THREAD

**Issue by schwabe93** [lssjbrolli/android_device_samsung_klimtlte-old#2]
Hi can you please share to mee a download link, i would test it :) , alos i build it on my own with your sources but i get into a bootloop after i flash it.

**Comment by lssjbrolli** [comment]
here you go: https://www.dropbox.com/s/hbc8tb5wjhx1c61/cm-11-20150125-UNOFFICIAL-klimtlte.zip?dl=0

feel free to test and add bug reports.

i also take patches :)

**Comment by schwabe93** [comment]
Can you share you your vendor blobs for the LTE Version, i use the wifi vendor blobs?

**Comment by lssjbrolli** [comment]
i use the blobs from T705XXU1ANF8_T705LUX1ANK1_LUX, u can find the image at http://www.sammobile.com/firmwares/download/39102/T705XXU1ANF8_T705LUX1ANK1_LUX/

**Comment by schwabe93** [comment]
OK and  and how do you extract them ? Form the file or the device?

**Comment by lssjbrolli** [comment]
you can do both, you run extract-files.sh with your device connected or you can download the file, extract images, comvert system image with simg2img, mount the converted image and then run extract-files.sh /path/to/mounted/system/

**Comment by schwabe93** [comment]
OK thanks for your help, but if i run that file one vor two files copy the it still says the file is missing. I looked at the property... and search in the vendor files of the t705 Firmware. There are a lots of Files missing

**Comment by lssjbrolli** [comment]
which repo are you using? this old one for cm-11 or the new one for cm-12?

**Comment by schwabe93** [comment]
The New one From eousphoros

**Comment by lssjbrolli** [comment]
in that case download the rom from xda and extract the blobs from it.

**Comment by schwabe93** [comment]
ok thanks it worked
